"""add name to user

Revision ID: 09f485ead800
Revises: e2c27ec023ce
Create Date: 2026-08-13 16:09:24.294506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09f485ead800'
down_revision: Union[str, Sequence[str], None] = 'e2c27ec023ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE users SET name = 'Antigravity'")
    op.alter_column('users', 'name', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
