"""add last action to contacts

Revision ID: 18014a7d8712
Revises: f98b6e342194
Create Date: 2026-08-13 15:10:17.866524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18014a7d8712'
down_revision: Union[str, Sequence[str], None] = 'f98b6e342194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import sqlmodel
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('last_action_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contacts', sa.Column('last_action_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    op.execute("UPDATE contacts SET last_action_status = 'Not Contacted' WHERE last_action_status IS NULL")
    op.execute("UPDATE users SET name = 'Owner' WHERE name IS NULL")
    
    op.alter_column('contacts', 'last_action_status', nullable=False)
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('contacts', 'last_action_date')
    op.drop_column('contacts', 'last_action_status')
    # ### end Alembic commands ###
