"""Add indexes for performance

Revision ID: 26770aed8b1e
Revises: 9c84c6925363
Create Date: 2026-08-27 01:25:43.446503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26770aed8b1e'
down_revision: Union[str, Sequence[str], None] = '9c84c6925363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_log_action_type'), 'activity_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_log_timestamp'), 'activity_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_applications_date_applied'), 'applications', ['date_applied'], unique=False)
    op.create_index(op.f('ix_applications_next_action_due'), 'applications', ['next_action_due'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_events_event_date'), 'calendar_events', ['event_date'], unique=False)
    op.drop_index(op.f('uq_contact_email'), table_name='contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_contact_email'), 'contacts', ['user_id', sa.literal_column('lower(email::text)')], unique=True)
    op.drop_index(op.f('ix_calendar_events_event_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_next_action_due'), table_name='applications')
    op.drop_index(op.f('ix_applications_date_applied'), table_name='applications')
    op.drop_index(op.f('ix_activity_log_timestamp'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action_type'), table_name='activity_log')
    # ### end Alembic commands ###
