"""add revoked_at to refresh_tokens

Revision ID: 5e320c09f7f5
Revises: 13bc7c511b5d
Create Date: 2026-08-13 23:11:19.486310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e320c09f7f5'
down_revision: Union[str, Sequence[str], None] = '13bc7c511b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###
