"""Add next_action fields

Revision ID: 77db924445d2
Revises: 45ebaa41d50b
Create Date: 2026-08-23 18:17:41.767136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77db924445d2'
down_revision: Union[str, Sequence[str], None] = '45ebaa41d50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('next_action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('next_action_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'next_action_title')
    op.drop_column('applications', 'next_action_type')
    # ### end Alembic commands ###
