"""add file_hash to resumes

Revision ID: b0921af9ce80
Revises: 09f485ead800
Create Date: 2026-08-13 16:44:03.389088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b0921af9ce80'
down_revision: Union[str, Sequence[str], None] = '09f485ead800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Give existing resumes a unique dummy hash based on their id
    op.execute("UPDATE resumes SET file_hash = md5(id::text)")
    op.alter_column('resumes', 'file_hash', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_hash')
    # ### end Alembic commands ###
