"""add daily calls goal

Revision ID: e2c27ec023ce
Revises: c9b8009e7463
Create Date: 2026-08-13 15:59:51.983863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2c27ec023ce'
down_revision: Union[str, Sequence[str], None] = 'c9b8009e7463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('daily_calls_goal', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'daily_calls_goal')
    # ### end Alembic commands ###
