"""Add notifications to settings

Revision ID: f98b6e342194
Revises: a29840d12ab2
Create Date: 2026-08-13 06:10:22.090896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98b6e342194'
down_revision: Union[str, Sequence[str], None] = 'a29840d12ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('calendar_events', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('daily_snapshots', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('resumes', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('settings', sa.Column('app_reminders', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('followup_reminders', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('interview_reminders', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('daily_progress', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('streak_alerts', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('settings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_email_lower'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_email_lower'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.alter_column('settings', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('settings', 'streak_alerts')
    op.drop_column('settings', 'daily_progress')
    op.drop_column('settings', 'interview_reminders')
    op.drop_column('settings', 'followup_reminders')
    op.drop_column('settings', 'app_reminders')
    op.alter_column('resumes', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('daily_snapshots', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('calendar_events', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applications', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('activity_log', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
